### PR TITLE
Most frequent used slash chords added.

### PR DESCRIPTION
**Pull request by szaza**

### CODE REVIEW

**Comment by szaza** [comment]
Please review. I'll add more chords later on a different branch.

**Comment by tombatossals** [comment]
Great contribution @szaza. We can bump the version when you finish adding all the chords you have. Thanks

**Comment by tombatossals** [comment]
I just updated the libraries to avoid using old and potentially vulnerable software.

I have made one change from your PR, the "chords/index.js" must return an object and not an array. That's because you can access quickier to the chords of the object. For example: guitar["C"] will return all the chords related to that key in an array.

I have fixed the tests too, found two typos in your chords. These tests help to found common mistakes.

**Comment by szaza** [comment]
"the 'chords/index.js' must return an object and not an array." - sorry I had to make some conversions, because I'm using your library with TypeScript and it didn't allow to refer to the object attributes as an associative array. Yap, unit tests are very useful!
Thanks for merging my branch, I'm going to add more chords as soon as I'll have some more time ;-)

**Comment by tombatossals** [comment]
@szaza I'm going to change the naming of your slash version of the chords. Insted of using AmsF I'm going to use Am_F. This is acceptable in the filesystem and will be easier to recognize them in the rendering.

**Pull request merged**
