### PR TITLE
Adds many chords

### PR DESCRIPTION
**Pull request by jthawme**
Hi there, thanks so much for this package, it is really helping with a project https://ultimate-guitarx.com/

I have created a pipeline to create many chords at once automatically, to hopefully give better parity for the library with what users create on the tab website ultimate-guitar.com hopefully you are happy with these being added to the library

So far there are:

- sus
- add11
- lots of '/' chords (i.e Em9/D)
- maj7sus2

Thank you

### CODE REVIEW

**Comment by tombatossals** [comment]
That's a fantastic patch. Glad to know someone finds this library interesting and set ups a useful resource as the project you're developing. 

If you want to continue evolving the database I can grant you the developer role. 

Thanks in any case!

**Comment by Kernix13** [comment]
FTI: `maj7sus2` is not a correct chord name. Any 7th that also has the major 2nd is a 9th, so that would be a `maj9` which is a beautiful-sounding chord

**Comment by jthawme** [comment]
> FTI: `maj7sus2` is not a correct chord name. Any 7th that also has the major 2nd is a 9th, so that would be a `maj9` which is a beautiful-sounding chord

very interesting! im not so knowledgeable with chord names, i am basing this mainly off of chord names that users have used on ultimate-guitar.com (this chord was in this tab https://tabs.ultimate-guitar.com/tab/neck-deep/a-part-of-me-chords-1201137)

But I do have control to actually alias chords too, so maybe i could use the opportunity to 'correct' the naming of some chords too this, thanks for the info!

**Comment by Kernix13** [comment]
There are a lot of 9's: add9, m add9, 9, m9, maj9, 9b5, 9#5, ...

I created a guitar chord naming app if you want to bounce your chords against what I have. Check it out at https://everyguitarchord.com/what-chord-is-this.html

Just make sure to select a tuning and sharp/flat. I recently changed how it works but forgot to add a warning if you don't select sharp/flat

**Pull request merged**
